### ISSUE TITLE
Error using somes plugins.

### ISSUE THREAD

**Issue by Mapacheee** [DivineMC/DivineMC#17]
### Expected behavior

All plugins working i expected to see.

### Observed/Actual behavior

I've this two errors:

Plugin FancyHolograms:

[22:17:18 INFO]: [FancyHolograms] Loading server plugin FancyHolograms v2.3.0
[22:17:18 ERROR]: [FancyHolograms] Error initializing plugin 'FancyHolograms-2.3.0.jar' in folder 'plugins' (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/world/level/Level
        at FancyHolograms-2.3.0.jar/de.oliver.fancyholograms.FancyHolograms.resolveHologramAdapter(FancyHolograms.java:224) ~[FancyHolograms-2.3.0.jar:?]
        at FancyHolograms-2.3.0.jar/de.oliver.fancyholograms.FancyHolograms.onLoad(FancyHolograms.java:88) ~[FancyHolograms-2.3.0.jar:?]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:553) ~[?:?]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:332) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1167) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.level.Level
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:146) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:107) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 11 more
        
- - - -- - -- - - -- - 
[22:17:30 INFO]: [FancyHolograms] Enabling FancyHolograms v2.3.0
[22:17:30 ERROR]: Error occurred while enabling FancyHolograms v2.3.0 (Is it up to date?)
java.lang.NullPointerException: plugin is not initialized
        at java.base/java.util.Objects.requireNonNull(Unknown Source) ~[?:?]
        at FancyHolograms-2.3.0.jar/de.oliver.fancyholograms.FancyHolograms.getHologramsManager(FancyHolograms.java:175) ~[FancyHolograms-2.3.0.jar:?]
        at FancyHolograms-2.3.0.jar/de.oliver.fancyholograms.FancyHolograms.onEnable(FancyHolograms.java:135) ~[FancyHolograms-2.3.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:647) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:369) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1167) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
[22:17:30 INFO]: [FancyHolograms] Disabling FancyHolograms v2.3.0
[22:17:30 ERROR]: Error occurred while disabling FancyHolograms v2.3.0
java.lang.NullPointerException: Cannot invoke "de.oliver.fancyholograms.HologramManagerImpl.saveHolograms()" because "this.hologramsManager" is null
        at FancyHolograms-2.3.0.jar/de.oliver.fancyholograms.FancyHolograms.onDisable(FancyHolograms.java:150) ~[FancyHolograms-2.3.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:237) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:114) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:550) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:647) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:369) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1167) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
        
        
        
 Plugin Terra:
 
 [22:17:23 ERROR]: Could not pass event WorldInitEvent to Terra v6.5.0-BETA+9e60db4b0
java.lang.RuntimeException: java.lang.NoSuchFieldException: worldGenContext
        at Terra-bukkit-6.5.0-BETA+e7cc27534-shaded.jar/com.dfsek.terra.bukkit.nms.v1_21.NMSInjectListener.onWorldInit(NMSInjectListener.java:57) ~[Terra-bukkit-6.5.0-BETA+e7cc27534-shaded.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:72) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:60) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.MinecraftServer.initWorld(MinecraftServer.java:707) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:660) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:369) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1167) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoSuchFieldException: worldGenContext
        at java.base/java.lang.Class.getDeclaredField(Unknown Source) ~[?:?]
        at Terra-bukkit-6.5.0-BETA+e7cc27534-shaded.jar/com.dfsek.terra.api.util.reflection.ReflectionUtil.setFinalField(ReflectionUtil.java:52) ~[Terra-bukkit-6.5.0-BETA+e7cc27534-shaded.jar:?]
        at Terra-bukkit-6.5.0-BETA+e7cc27534-shaded.jar/com.dfsek.terra.bukkit.nms.v1_21.NMSInjectListener.onWorldInit(NMSInjectListener.java:49) ~[Terra-bukkit-6.5.0-BETA+e7cc27534-shaded.jar:?]
        ... 13 more
        
        

Plugin FartherViewDistance:

[22:17:30 INFO]: [FartherViewDistance] Enabling FartherViewDistance v9.9.2
[22:17:30 ERROR]: Error occurred while enabling FartherViewDistance v9.9.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/nbt/Tag
        at FartherViewDistance.jar/xuan.cat.fartherviewdistance.code.branch.v121.Branch_121_Packet.<init>(Branch_121_Packet.java:24) ~[FartherViewDistance.jar:?]
        at FartherViewDistance.jar/xuan.cat.fartherviewdistance.code.ChunkIndex.onEnable(ChunkIndex.java:124) ~[FartherViewDistance.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:647) ~[?:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:596) ~[?:?]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:369) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1167) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[divinemc-1.21.jar:1.21-DEV-ecf4387]
        at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.minecraft.nbt.Tag
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:197) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:164) ~[paper-mojangapi-1.21-R0.1-SNAPSHOT.jar:?]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
        ... 14 more
[22:17:30 INFO]: [FartherViewDistance] Disabling FartherViewDistance v9.9.2
        
        
        

### Steps/models to reproduce

Just installing plugins

### DivineMC version

1.21 DEV ecf4387 (MC 1.21) - Lastest version in this moment

### Agreements

- [X] I am running the latest version of DivineMC from [here](https://github.com/DivineMC/DivineMC/releases/latest).
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by DivineMC.

### Other

thank you very much for creating this fork, I have better performance even though some plugins have problems.

**Comment by mapacheee** [comment]
i didnt say nothing, i tested with mojmap jar and everything goes nice

**Comment by NONPLAYT** [comment]
from 1.20.5/1.20.6 you need to use mojmapped server jar, instead of reobf. And I tested all plugin, everything works perfectly except Terra, because there is no official support for it on 1.21, which is why it does not load
